#!/bin/sh

# Homebrew Script for OSX
# To execute: save and `chmod +x ./brew-install-script.sh` then `./brew-install-script.sh`

echo "Installing brew..."
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Installing brew cask..."
brew tap caskroom/cask

# Programming Languages
brew cask install java
brew install node
brew install qt

# Python and Python Modules
brew install python
brew install python3
pip3 install requests
pip install requests

#Dev Tools
brew install git
brew install pandoc
brew install bash-completion
brew install vim
brew install ctags
brew install screen

# Application
brew cask install google-chrome
brew cask install firefox
brew cask install dashlane
brew cask install spectacle
brew cask install xquartz
brew cask install amazon-music
brew cask install vlc

