#!/bin/sh

echo "Installing brew..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Taps.
brew tap aws/tap
brew tap sdkman/tap
brew tap 1password/tap

# Packages.
brew install aws-sam-cli
brew install awscli
brew install bash
brew install bash-completion
brew install docker
brew install gh
brew install git
brew install jq
brew install node
brew install pandoc
brew install pyenv
brew install sdkman-cli
brew install tmux
brew install vim

# Casks.
brew install --cask 1password
brew install --cask 1password-cli
brew install --cask clion
brew install --cask google-chrome
brew install --cask intellij-idea
brew install --cask iterm2
brew install --cask jabra-direct  # Headphones.
brew install --cask logitech-camera-settings  # Webcam.
brew install --cask rectangle
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask xquartz
brew install --cask zoom
