#!/bin/sh

usage() {
  echo "Usage: $0 [--no-casks]"
  echo "  --no-casks   Skip installing cask applications"
  echo "  --help, -h   Show this help message"
  exit 0
}

# Process args.
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  usage
fi

[ "$1" = "--no-casks" ] && NO_CASKS=true || NO_CASKS=false

echo "Installing brew..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Taps.
brew tap aws/tap
brew tap sdkman/tap
brew tap 1password/tap

# Packages.
brew install aspell
brew install aws-sam-cli
brew install awscli
brew install bash
brew install bash-completion
brew install gh
brew install git
brew install git-lfs
brew install htop
brew install imagemagick
brew install jq
brew install node
brew install pam-reattach  # For tmux touch auth.
brew install pandoc
brew install python-tk
brew install pyenv
brew install rbenv ruby-build  # Ruby for personal site.
brew install sdkman-cli
brew install tmux
brew install tree
brew install vim
brew install wget

# Exit if --no-casks was provided.
$NO_CASKS && exit 0

# Casks.
brew install --cask 1password
brew install --cask 1password-cli
brew install --cask clion
brew install --cask docker
brew install --cask google-chrome
brew install --cask intellij-idea
brew install --cask iterm2
brew install --cask jabra-direct  # Headphones.
brew install --cask logitech-camera-settings  # Webcam.
brew install --cask rectangle
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask xquartz
brew install --cask zoom

