# Set path.
PATH=$PATH:$HOME/bin/                  # Directory for any scripts we create.
PATH=$PATH:$HOME/Qt/5.8/clang_64/bin   # QT.
PATH=$PATH:/usr/local/opt/             # coreutils export PATH

# Explicitly set TERM variable. Needed for screen to play nice with vim.
export TERM=xterm-256color

# Use vi for terminal
set -o vi

# Ignore these files on tab completion.
export FIGNORE=$FIGNORE:.o:.class:.pyc

# Define all aliases in bash_aliases.
if [ -f $HOME/.bash_aliases ]; then
    source $HOME/.bash_aliases;
fi

# Set my default editor to vim.
export VISUAL=vim
export EDITOR=$VISUAL

# Prettify ls command.
export LSCOLORS=ExFxBxDxCxegedabagacad

# Two line command prompt. First line is cwd. Second is typical user/host stuff.
bold=$(tput bold);
reset=$(tput sgr0)
green=$(tput setaf 2);
yellow=$(tput setaf 3);
cyan=$(tput setaf 6);
white=$(tput setaf 7)
export PS1="\[$yellow\][\w]\n\[$cyan\]\u\[$white\]@\[$green\]\h:\[$white\]\$ \[$reset\]"
export CLICOLOR=1
