# Set path.
PATH=$HOME/bin/:$PATH    # Directory for any scripts we create.
PATH=$PATH:/opt/bin/
PATH=$PATH:/usr/local/opt/                   # coreutils export PATH
PATH=$PATH:~/.cargo/bin

export PATH

export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home


#GIT_PROMPT_ONLY_IN_REPO=1
#source ~/.bash-git-prompt/gitprompt.sh

# Store bash history in one file. Not uniquely per terminal session.
export SHELL_SESSION_HISTORY=0

export PYTHONSTARTUP=$HOME/.pythonrc

# Store our history files in the .history directory.
export HISTSIZE=
# Ignore lines that duplicates of the previous line.
export HISTCONTROL=ignoredups
export HISTFILE=$HOME/.history/bash_history
export LESSHISTFILE=$HOME/.history/lesshist

# Explicitly set TERM variable. Needed for screen to play nice with vim.
export TERM=xterm-256color

# Use vi for bash. Note this is redundant since everything that uses
# readline (which includes bash) is already set to use vi in our inputrc.
set -o vi

# Ignore these files on tab completion.
export FIGNORE=$FIGNORE:.o:.class:.pyc

# Define all aliases in bash_aliases.
if [ -f $HOME/.bash_aliases ]; then
    . $HOME/.bash_aliases;
fi

if [ -f $HOME/.bash_functions ]; then
    . $HOME/.bash_functions;
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Set my default editor to vim.
export VISUAL=vim
export EDITOR=$VISUAL

# Prettify ls command.
export LSCOLORS=ExFxBxDxCxegedabagacad

# Two line command prompt. First line is cwd. Second is typical user/host stuff.
bold=$(tput bold);
reset=$(tput sgr0)
green=$(tput setaf 2);
yellow=$(tput setaf 3);
cyan=$(tput setaf 6);
white=$(tput setaf 7)
export PS1="\[$yellow\][\w]\n\[$cyan\]\u\[$white\]@\[$green\]\h:\[$white\]\$ \[$reset\]"
export CLICOLOR=1
