#!/bin/bash
ymln() {
 ln -s $1 $(basename -s .template $1).yaml
}

startvm() {
    vboxmanage startvm ubuntu --type headless
}

entervm() {
    startvm
    #ssh vbox
}

stopvm() {
    vboxmanage controlvm ubuntu poweroff
}

pausevm() {
    vboxmanage controlvm ubuntu pause 
}

resumevm() {
    vboxmanage controlvm ubuntu resume
}

savevm() {
    vboxmanage controlvm ubuntu savestate
}

# TODO (nphair): Replace the head | tail bit with sed -n '1p'
docker-exec-mru() {
    docker ps | head -2 | tail -1 | awk '{ print $1 }' | xargs -o -I{} docker exec -it {} /bin/bash
}

docker-rm-mru() {
    docker ps -a | head -2 | tail -1 | awk '{ print $1 }' | xargs -I{} docker rm {}
}

docker-rmi-repo() {
    REPO=$1
    docker ps -a | grep $REPO | awk '{ print $1 }' | xargs -I{} docker rmi {}
}

jim-mode() {
    bind -f  ~/.jimputrc
}

nick-mode() {
    bind -f  ~/.inputrc
}

popTempD() {
  TMP="$(dirs -1)" 
  popd
  rm -rf ${TMP}
}

mkbk() {
  cp ${1}{,.bak}
}
